blog_index:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_category:
  path: /{categorySlug}
  defaults: { _controller: BlogBundle:Blog:category}
  requirements:
    categorySlug: '[^/]+'

blog_post:
  path: /{categorySlug}/{postSlug}
  defaults: {_controller: BlogBundle:Blog:post}
  requirements:
    categorySlug: '[^/]+'
    postSlug: '[^/]+'